/** Declaration file generated by dts-gen */

export function allLoadavg(): any;

export function cpuCount(): any;

export function cpuFree(callback: any): void;

export function cpuUsage(callback: any): void;

export function freeCommand(callback: any): void;

export function freemem(): any;

export function freememPercentage(): any;

export function getProcesses(nProcess: any, callback: any): void;

export function harddrive(callback: any): void;

export function loadavg(_time: any): any;

export function platform(): any;

export function processUptime(): any;

export function sysUptime(): any;

export function totalmem(): any;

export namespace allLoadavg {
    const prototype: {
    };

}

export namespace cpuCount {
    const prototype: {
    };

}

export namespace cpuFree {
    const prototype: {
    };

}

export namespace cpuUsage {
    const prototype: {
    };

}

export namespace freeCommand {
    const prototype: {
    };

}

export namespace freemem {
    const prototype: {
    };

}

export namespace freememPercentage {
    const prototype: {
    };

}

export namespace getProcesses {
    const prototype: {
    };

}

export namespace harddrive {
    const prototype: {
    };

}

export namespace loadavg {
    const prototype: {
    };

}

export namespace platform {
    const prototype: {
    };

}

export namespace processUptime {
    const prototype: {
    };

}

export namespace sysUptime {
    const prototype: {
    };

}

export namespace totalmem {
    const prototype: {
    };

}

